# Generated by Django 4.1.5 on 2023-11-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrioUsers',
        ),
    ]
