# Generated by Django 4.1.5 on 2023-12-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('front', '0002_delete_triousers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('--select--', '--select--'), ('3D Printing & Robotics', '3D Printing & Robotics'), ('Automobile & Vehicles', 'Automobile & Vehicles'), ('Air Transport', 'Air Transport'), ('Business', 'Business'), ('Classes', 'Classes'), ('Clothing', 'Clothing'), ('Community', 'Community'), ('Construction & Farming Equipments', 'Construction & Farming Equipments'), ('Electronics', 'Electronics'), ('Freelancing', 'Freelancing'), ('Furniture', 'Furniture'), ('Insurance', 'Insurance'), ('Jobs', 'Jobs'), ('Matrimonial', 'Matrimonial'), ('Pets', 'Pets'), ('Real Estate, Housing & Rentals', 'Real Estate, Housing & Rentals'), ('Sales', 'Sales'), ('Services', 'Services'), ('Softwares', 'Softwares'), ('Space & Astronomy', 'Space & Astronomy'), ('Tickets', 'Tickets'), ('Travels, Holiday & Leisure', 'Travels, Holiday & Leisure'), ('Others...', 'Others')], max_length=50)),
                ('condition', models.CharField(choices=[('--select--', '--select--'), ('New', 'New'), ('Used-New', 'Used-New'), ('Used-Good', 'Used-Good'), ('Used-Fair', 'Used-Fair')], max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('delivery', models.CharField(choices=[('--select--', '--select--'), ('willing to drop off', 'willing to drop off'), ('willing to ship Item', 'willing to ship Item'), ('Offer curbside Pickup', 'Offer curbside Pickup')], max_length=50)),
                ('media', models.FileField(upload_to='')),
                ('location', models.CharField(choices=[('--select--', '--select--'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland & Labrador', 'Newfoundland & Labrador'), ('NorthWest Territories', 'NorthWest Territories'), ('Nova Scotia', 'Nova Scotia'), ('Nuna Vut', 'Nuna Vut'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Tukon Territory', 'Tukon Territory')], max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('payment', models.CharField(choices=[('--select--', '--select--'), ('cash', 'cash'), ('Cashless', 'cashless'), ('Cash or Cashless', 'cash or cashless')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
