# Generated by Django 4.1.5 on 2023-12-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='media',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('3D Printing & Robotics', '3D Printing & Robotics'), ('Automobile & Vehicles', 'Automobile & Vehicles'), ('Air Transport', 'Air Transport'), ('Business', 'Business'), ('Classes', 'Classes'), ('Clothing', 'Clothing'), ('Community', 'Community'), ('Construction & Farming Equipments', 'Construction & Farming Equipments'), ('Electronics', 'Electronics'), ('Freelancing', 'Freelancing'), ('Furniture', 'Furniture'), ('Insurance', 'Insurance'), ('Jobs', 'Jobs'), ('Matrimonial', 'Matrimonial'), ('Pets', 'Pets'), ('Real Estate, Housing & Rentals', 'Real Estate, Housing & Rentals'), ('Sales', 'Sales'), ('Services', 'Services'), ('Softwares', 'Softwares'), ('Space & Astronomy', 'Space & Astronomy'), ('Tickets', 'Tickets'), ('Travels, Holiday & Leisure', 'Travels, Holiday & Leisure'), ('Others...', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used-New', 'Used-New'), ('Used-Good', 'Used-Good'), ('Used-Fair', 'Used-Fair')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='delivery',
            field=models.CharField(choices=[('willing to drop off', 'willing to drop off'), ('willing to ship Item', 'willing to ship Item'), ('Offer curbside Pickup', 'Offer curbside Pickup')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland & Labrador', 'Newfoundland & Labrador'), ('NorthWest Territories', 'NorthWest Territories'), ('Nova Scotia', 'Nova Scotia'), ('Nuna Vut', 'Nuna Vut'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Tukon Territory', 'Tukon Territory')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='payment',
            field=models.CharField(choices=[('cash', 'cash'), ('Cashless', 'cashless'), ('Cash or Cashless', 'cash or cashless')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='Adimages/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.ad')),
            ],
        ),
    ]
