# Generated by Django 4.1.5 on 2023-12-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_ad_category_alter_adimages_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('3D Printing & Robotics', (('3D Printing Technology', '3D Printing Technology'), ('Roboticts', 'Robotics'))), ('Automobile & Vehicles', (('ATVs & Snowmobiles', 'ATVs & Snowmobiles'), ('Bikes, Boats & Watercraft', 'Bikes, Boats & Watercraft'), ('Cars & Heavy Trucks', 'Cars & Heavy Trucks'), ('Damaged & Accident Vehicles', 'Damaged & Accident Vehicles'), ('Automobile Dealers', 'Automobile Dealers'), ('Driving Schools', 'Driving Schools'), ('Parts, Tires, & Accessories', 'Parts, Tires, & Accessories'), ('Rentals, Lease & Financing', 'Rentals, Lease & Financing'), ('RoadSide Assistance', 'RoadSide Assistance'))), ('Air Transport', (('Aircrafts & Airplanes', 'Aircrafts & Airplanes'), ('Aircraft Dealers', 'Aircraft Dealers'), ('Flight Schools', 'Flight Schools'), ('Parts, Tires, & Accessories', 'Parts, Tires, & Accessories'), ('Rentals, Lease & Financing', 'Rentals, Lease & Financing'))), ('Business', (('Renting', 'Renting'), ('Opportunities', 'Opportunities'), ('Cryptocurrencies', 'Cryptocurrencies'), ('Finance & Investments', 'Finance & Investments'), ('Franchise/ Trading', 'Franchise/ Trading'), ('Partnership & Joint Ventures', 'Partnership & Joint Ventures'))), ('Classes', (('Art, Music & Dance Classes', 'Art, Music & Dance Classes'), ('Computer - Multimedia Classes', 'Computer - Multimedia Classes'), ('Continuing Education', 'Continuing Education'), ('Language Classes', 'Language Classes'), ('Online Bootcamps & Mastermind', 'Online Bootcamps & Mastermind'), ('Sports & Wellness Classes', 'Sports & Wellness Classes'), ('Tutoring - Private Lessons', 'Tutoring - Private Lessons'))), ('Clothing', ()), ('Community', ()), ('Construction & Farming Equipments', ()), ('Electronics', ()), ('Freelancing', ()), ('Furniture', ()), ('Insurance', ()), ('Jobs', ()), ('Matrimonial', ()), ('Pets', 'Pets'), ('Real Estate, Housing & Rentals', ()), ('Sales', ()), ('Services', ()), ('Softwares', ()), ('Space & Astronomy', ()), ('Tickets', ()), ('Travels, Holiday & Leisure', ()), ('Others...', ())], max_length=50),
        ),
    ]
