# Generated by Django 4.1.5 on 2023-12-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_alter_ad_options_alter_adimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used-New', 'Used-New'), ('Used-Good', 'Used-Good'), ('Used-Fair', 'Used-Fair')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='delivery',
            field=models.CharField(choices=[('willing to drop off', 'willing to drop off'), ('willing to ship Item', 'willing to ship Item'), ('Offer curbside Pickup', 'Offer curbside Pickup')], max_length=50, null=True),
        ),
    ]
