# Generated by Django 4.1.5 on 2024-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_remove_ad_email_remove_ad_phone_alter_ad_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
